name: Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Async Github Branch To Gitee
      uses: MK-zz/vite-auto-pinia@mian
      with:
        github_repo: MK-zz/vite-auto-pinia
        github_branch: mian
        gitee_repo: 小太白/vite-auto-pinia
        gitee_branch: master
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}