name: Sync to Gitee

on:
  push:
    branches:
      - main # 指定您的 GitHub 分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Gitee 
      run: |
        git remote add gitee https://gitee.com/xiaotaibai123/vite-auto-pinia.git
        git push gitee main:main # 指定您的 Gitee 分支
      env:
        GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
